# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.CharField(default='/weblog/img/user.png', max_length=200),
        ),
    ]
