# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0003_auto_20161017_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_cropped',
            field=models.CharField(default='/static/weblog/img/user.png', max_length=200),
        ),
    ]
